### ISSUE TITLE
Enable FrameProcessor for camera2

### ISSUE THREAD

**Issue by hateum** [Fotoapparat/Fotoapparat#110]
Hi,

How to enable FrameProcessor on camera2 ?

**Comment by dmitry-zaitsev** [comment]
Unfortunately due to Camera2 issues we are not supporting frame processors in Camera2.

Here is a related issue on StackOverflow:
https://stackoverflow.com/q/43687624/926907

In general, from our experience Camera1 seems to work surprisingly better than Camera2. In fact, Camera2 is a lower level API than Camera1 and even harder to work with, so we are not focusing on it as much and the default configuration of Fotoapparat is using Camera1.
