### ISSUE TITLE
Issue About After Take a Picture

### ISSUE THREAD

**Issue by 1060680253** [Fotoapparat/Fotoapparat#43]
After taking pictures will be stuck for a while, this problem can be improved?But the system camera after taking pictures, will not be stuck for a while
Please help me out this problem。thankyou

**Comment by Diolor** [comment]
Hi! Can you please give more concrete details? What stuck means? And also what phone/api versions did you experience it with?

**Comment by 1060680253** [comment]
![gif_20170619_162730](https://user-images.githubusercontent.com/15134794/27277399-b63c8228-5510-11e7-854f-2eaeedabca65.gif)

you can see gif file，phone version is android 5.0.2

**Comment by dmitry-zaitsev** [comment]
Sorry for slow reply. 

I looked into the issue and it seems that the root cause is that we are using Camera1 API by default since it is generally faster, less complicated and more reliable. You can switch to Camera2 API, which will fix that particular problem. 

Here is how you can do it. When you prepare your `Fotoapparat` instance, just provide `cameraProvider` parameter like that.

```
.cameraProvider(v2(context))
```
