### ISSUE TITLE
Manual Focus

### ISSUE THREAD

**Issue by Jameido** [Fotoapparat/Fotoapparat#60]
Hi there, 
it's possible to let the user choose which part of the picture should be focused manually? 
Like on the default android camera, when the use taps on the screen it should set the focus on that area, as shown in the attached gif

![camera_manual_focus](https://user-images.githubusercontent.com/6197669/28264475-5d9e7bee-6aeb-11e7-8fac-24a3dfe49b7c.gif)

**Comment by dmitry-zaitsev** [comment]
Are you looking for a way to focus on a specific point on a picture or just tap-to-focus feature? The former is not yet implemented, the latter is already available.

**Comment by Jameido** [comment]
I'm looking for the first one, it would be a nice add to this amazing library ✨

**Comment by TemMax** [comment]
+1. Add please feature for focus on specific point and pinch-to-zoom feature.
Thanks for wonderful library!

**Comment by dmitry-zaitsev** [comment]
Sorry guys, this feature will not make it into 1.3.0 as it is a bit tricky to implement. We will implement it as part of 1.4.0.

Also, if someone is eager to help - please contact me. I can provide the directions on how to implement this feature in the library.

**Comment by friendoye** [comment]
@dmitry-zaitsev I would like to step in, if you don't mind.

**Comment by dmitry-zaitsev** [comment]
@friendoye that would be great!

First of all, let's forget about Camera2 for now. We do not actively support it anymore (since it is surprisingly more buggy than Camera1), so let's focus on Camera1.

To focus on the specific area we can use `Camera.Parameters.setFocusAreas`. There are some caveats though:

- We should first call `getMaxNumFocusAreas()` to check if focus areas are supported at all.
- We need to map user touches to `Area` class. But camera preview stream might actually be bigger than the size of the actual view. There is a handy layout which we use for something similar in our `FaceDetector` library - [CameraOverlayLayout](https://github.com/Fotoapparat/FaceDetector/blob/master/Android/facedetector/src/main/java/io/fotoapparat/facedetector/view/CameraOverlayLayout.java) We might just copy it into `Fotoapparat`. I believe people who work with Computer Vision will find it very handy.
- Area coordinates are in camera sensor space, which means that they are different from what user sees on his screen. That means that we have to rotate the area (and possibly even mirror it) before calling `setFocusAreas`. `OrientationUtils` might come in handy here.

**Comment by friendoye** [comment]
@dmitry-zaitsev hmm, sounds interesting! I'll start working on PR this week.

**Comment by abodehBabelli** [comment]
@friendoye is there any estimated date to finish adding manual focus??

**Comment by friendoye** [comment]
@abodehBabelli I'm planning to submit PR at the end of this week. It will include tap to focus feature for Camera1 API.

**Comment by Diolor** [comment]
@ all. Tap to focus feature has been included in v2.1 🎉

**Comment by alexischenko** [comment]
Can someone help? I can't find focusView method in Fotoapparat builder class. I'm using version 2.2.0

**Comment by Diolor** [comment]
Did you check the sample?

**Comment by Avalin** [comment]
I copied the sample to my project, and the focusView is for some reason not being recognised on mine either. Rest works.

**Comment by chungyau97** [comment]
@Diolor @friendoye @Avalin 
How to achieve fix value manual focus instead of using tap assisted focus?
#374 (comment)
