### ISSUE TITLE
photoResult not full view in imageview

### ISSUE THREAD

**Issue by faketon** [Fotoapparat/Fotoapparat#64]
photoResult not full view in imageview what i miss ?

i try to setScaleType in imageview but not work.
can you explane me what i miss ?

**Comment by faketon** [comment]
But i use Glide to help load image from path file. it can full view.
But i want to know this lib can help or not. Thank you for lib

**Comment by Diolor** [comment]
This library has nothing to do with loading images to an imageview. Please see https://developer.android.com/reference/android/widget/ImageView.ScaleType.html

**Comment by bruferrari** [comment]
I also have this problem and even using scaleType it does not fit the entire screen, I also had changed the sample and can't achieve the expected results.

**Comment by dmitry-zaitsev** [comment]
@faketon @bruferrari could you please provide screenshots for the problem? It would be easier to understand what the problem is.

**Comment by bruferrari** [comment]
Hi @dmitry-zaitsev here are some pics to better describe the mentioned problem, note that with any kind of scaleType that I'd used the image does not goes beyond that limit and I have the CameraView with width and height in match_parent.

Please do not pay so much attention on that odd floating FAB, I was trying everything to solve the problem even swap between ConstraintLayout to FrameLayout in order to note some changes but without success.

![screenshot_20170731-181804](https://user-images.githubusercontent.com/7285376/28850002-60c81602-76f0-11e7-8c93-6e9e2dadd1e3.png)
`scaleType="fitXY"`

![1501535879661](https://user-images.githubusercontent.com/7285376/28850006-647dc2ce-76f0-11e7-819c-aad75c9ed134.jpg)
`original photo saved`

![screenshot_20170731-183046](https://user-images.githubusercontent.com/7285376/28850017-7272bc7c-76f0-11e7-9dd2-2b4fd74cdaac.png)
`without scale type`

**Comment by faketon** [comment]
i fix my problem by use glide to load image from path. if you use bitmap from photoResult to set in imageview that photo can't full view. @bruferrari that is my resovled

**Comment by dmitry-zaitsev** [comment]
Note that in sample app we are using `scaled ()` when taking a photo. Removing that should solve your problem.
